version: 2

sources:
  - name: core
    tables:
      - name: raw_amzn_books_data
        external:
          location: 'core/raw_amzn_books_data.csv'
      - name: raw_amzn_books_rating
        external:
          location: 'core/raw_amzn_books_rating.csv'
