
version: 2

models:
  - name: amzn_books_data_all
    description: "A starter dbt model"
    columns:
      - name: Title
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

